### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by sunnyzhong812** [SkalskiP/make-sense#118]
**Describe the bug**
Failed to compile.

**To Reproduce**
1. I try install and start ,Ubuntu 16.04 and 20.04 is same error.
2. See error

**Screenshots**
![err](https://user-images.githubusercontent.com/40876366/94394731-9adc9d80-0190-11eb-9770-f31a21f138d4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu16.04.7 / 20.04
 - Browser :Firefox
 - Version node 11.15.0, npm 6.7.0

**Comment by SkalskiP** [comment]
Hi @sunnyzhong812 ! Could you please do `npm list -g --depth=1` inside `make-sense` dir?

**Comment by SkalskiP** [comment]
Hi @sunnyzhong812 ! Could you execute `npm list react-spinners`  inside the main `make-sense` dir?

**Comment by sunnyzhong812** [comment]
> 
> 
> Hi @sunnyzhong812 ! Could you execute `npm list react-spinners` inside the main `make-sense` dir?

Hi @SkalskiP ,
![err2](https://user-images.githubusercontent.com/40876366/94399423-e3e51f80-0199-11eb-943d-509f5dcadce0.png)

 Thank you

**Comment by SkalskiP** [comment]
@sunnyzhong812 The reason that the application does not start correctly is the inappropriate version of this library. Which is very strange because `npm install` should use the version defined in `package.json`. Try to change the library version manually to `0.5.4`. Try `npm install react-spinners@0.5.4` inside `make-sense` dir.

**Comment by sunnyzhong812** [comment]
@SkalskiP It's ok.
Because when I installed, used "sudo npm audit fix --production --unsafe-perm=true --allow-root".
