### ISSUE TITLE
Add and rename Labels after creating

### ISSUE THREAD

**Issue by rebotnix** [SkalskiP/make-sense#15]
It would be great when we can add new labels after creating a new project or that we can rename existing labels during the labeling process. This is not an issue, more a feature request.

**Comment by SkalskiP** [comment]
@rebotnix, you just want to be able to change the names of already created labels? Or do you want to be able to edit the entire list? So you want to add, remove labels and edit names?

**Comment by rebotnix** [comment]
@SkalskiP yes, add, remove labels and images would be very useful.

**Comment by SkalskiP** [comment]
@rebotnix I talked about it on Twitter today, I don't know if it's you or anyone else. The idea itself is very good and was originally in the range that was supposed to be in the alpha version, but due to the fact that other key functionalities took too long to complete, they were removed.

- Expanding the dataset with new images is quite simple and should be feasible without any problems.
- Editing the list of labels is more complicated. Mainly because once the project is open and we start to label the photos, we create a relationship between the photo and the label. In this situation, any operations on the labels list, such as changing the order or removing the label, may cause problems. This is because the photo is linked to the label index. Any changes of this type must be made carefully and thoroughly tested. But I also think that such functionality would bring a lot.

**Comment by rebotnix** [comment]
@SkalskiP I fully understand. Maybe it´s possible to resort the whole array with a progress box when it takes longer to rename. In the long term of this application, it makes all sense to use a database as backend and a project selector as the first login. I think you want to make the tools as small as possible and I like the idea of database-less server application for labeling. 

I´a c++ programmer and I worked in last 12 month a lot with nodejs and plain jquery and build some nice backends and frontend with it. The react framework is not my favorite right now, but this project makes sense to support it. I will experiment with it and try to see if i can implement the video to image part. Here we can work with standard binary on the backend or everything in JS which can be slow when we want to decode the video frame.

Keep up the good work. I really like it.

**Comment by SkalskiP** [comment]
@rebotnix I have decided that we will implement this issue in stages. The first step will be to add new photos while working on the project. I will start working on this part right now.

**Comment by SkalskiP** [comment]
Hi @rebotnix! This issue is coming to an end. On the develop branch and on the developer instance https://develop.makesense.ai/ this functionality is now available. And with the next release it will be added to the application.
