### ISSUE TITLE
Scrolling label

### ISSUE THREAD

**Issue by RaccoonForever** [SkalskiP/make-sense#40]
I have 8 different labels.
When I add more than 20 (more or less, it depends on the screen) boxes on one image. If I add one more bounding box. I won't be able to scroll down to all labels. I'll be able to pick only first ones.

See the screenshot linked. I have more labels under wheat but I can't access them.
![make-sense](https://user-images.githubusercontent.com/4057852/64180789-ab272980-ce65-11e9-932f-535732bfb857.png)

**Desktop **
 - OS: Windows 10
 - Browser : Firefox
 - Version : 60.0.2 (32 bits)

**Comment by SkalskiP** [comment]
Hi, @RaccoonForever It seems that because a dopdown containing your labels is always placed below the record you are editing, there are some problems when the record is too low. And the dropdown can't fit. A possible fix should not be difficult. I think we will publish it with the next release. Thank you for drawing attention to this problem. I'll keep you informed of any progress.

**Comment by SkalskiP** [comment]
Hi, @RaccoonForever Improvements have been made. They are currently available on the developer instance. https://develop.makesense.ai/ I encourage you to test and possibly further comments. The patch will enter the production instance with the next release.

**Comment by RaccoonForever** [comment]
Hello @SkalskiP.
Thanks for your answer and for your quick improvement !

It works like a charm on the test environment !

**Comment by SkalskiP** [comment]
Hi @RaccoonForever! I'm super happy to have managed to fix it!

**Comment by SkalskiP** [comment]
Hi, @RaccoonForever! Due to the large amount of bugs that we have managed to fix recently, we decided to make a small release marked with the tag `1.2.1-alpha`. The same applies to this issue, which is now available at https://makesense.ai 

Happy Labelling!
