### ISSUE TITLE
Image classification option

### ISSUE THREAD

**Issue by davidggphy** [SkalskiP/make-sense#81]
The tool is great, but the object detection utility is an overkill for image classification.
Are you gonna add the possibility to use make-sense for image classification.

Thanks for the great work!

**Comment by SkalskiP** [comment]
Hi @davidggphy, Thank you for your kind words about MakeSense. As you can see, just before entering the editor, the choice between Image classification and Object detection appears. Of course, this choice is an illusion at this point, because the Image classification button is inactive. But we're about to start working on the MakeSense beta version. Image classification for 100% will be part of this version because there are users who need this option.

**Comment by SkalskiP** [comment]
@davidggphy PR providing new functionality - image classification labeling is now open - https://github.com/SkalskiP/make-sense/pull/92

**Comment by SkalskiP** [comment]
This functionality is available on makesense.ai
